# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.runs/synth_1/.Xil/Vivado-18328-DESKTOP-21NJNHC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {{C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/bridge}} {
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/new/LED_blinker.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/new/LED_core.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/new/Wrapper.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/uart/baud_gen.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_gpi.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_gpo.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/bridge/chu_mcs_bridge.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_support/chu_mmio_controller.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_basic/chu_timer.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/uart/chu_uart.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_support/fifo/fifo.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_support/fifo/fifo_ctrl.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/subsys/mmio_sys_vanilla.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/mmio_support/fifo/reg_file.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/new/timer_ms.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/new/top.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/uart/uart.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/uart/uart_rx.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/mmio/uart/uart_tx.sv}
      {C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/top/mcs_top_vanilla.sv}
    }
      rt::read_verilog -sv -include {{C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/bridge}} C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {{C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/sources_1/imports/hdl/sys/bridge}} {
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/synth/bd_3914.v}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/synth/cpu.v}
    }
      rt::read_vhdl -lib microblaze_v11_0_6 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_0/hdl/microblaze_v11_0_vh_rfs.vhd}}
      rt::read_vhdl -lib xil_defaultlib {
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_0/synth/bd_3914_microblaze_I_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_1/synth/bd_3914_rst_0_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_2/synth/bd_3914_ilmb_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_3/synth/bd_3914_dlmb_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_4/synth/bd_3914_dlmb_cntlr_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_5/synth/bd_3914_ilmb_cntlr_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_6/synth/bd_3914_lmb_bram_I_0.vhd}
      {c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_7/synth/bd_3914_iomodule_0_0.vhd}
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_1/hdl/lib_cdc_v1_0_rfs.vhd}}
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_1/hdl/proc_sys_reset_v5_0_vh_rfs.vhd}}
      rt::read_vhdl -lib lmb_v10_v3_0_11 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_2/hdl/lmb_v10_v3_0_vh_rfs.vhd}}
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_19 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_4/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd}}
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_6/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd}}
      rt::read_vhdl -lib iomodule_v3_1_7 {{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_7/hdl/iomodule_v3_1_vh_rfs.vhd}}
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2021.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mcs_top_vanilla
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.runs/synth_1/.Xil/Vivado-18328-DESKTOP-21NJNHC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
