set_property SRC_FILE_INFO {cfile:{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc} rfile:../../../../../FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_0/bd_3914_microblaze_I_0.xdc id:1 order:EARLY scoped_inst:cpu_unit/inst/microblaze_I/U0} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc} rfile:../../../../../FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_1/bd_3914_rst_0_0.xdc id:2 order:EARLY scoped_inst:cpu_unit/inst/rst_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc} rfile:../../../../../FPGA_vanilla.gen/sources_1/ip/cpu/bd_0/ip/ip_3/bd_3914_dlmb_0.xdc id:3 order:EARLY scoped_inst:cpu_unit/inst/dlmb/U0} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc} rfile:../../../../../FPGA_vanilla.srcs/constrs_1/imports/constraint/Nexys4_DDR_chu.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Jordan/OneDrive/College/Engineering/System on Chip/FPGA_vanilla/FPGA_vanilla.runs/synth_1/dont_touch.xdc} rfile:../../../dont_touch.xdc id:5} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins cpu_unit/inst/microblaze_I/U0/Reset]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins [list cpu_unit/inst/rst_0/U0/EXT_LPF/ACTIVE_HIGH_EXT.ACT_HI_EXT/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D cpu_unit/inst/rst_0/U0/EXT_LPF/ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to/D]]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins cpu_unit/inst/dlmb/U0/SYS_Rst]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/microblaze_I/U0]
set_property src_info {type:XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/rst_0/U0]
set_property src_info {type:XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/dlmb/U0]
set_property src_info {type:XDC file:5 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/iomodule_0/U0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/microblaze_I]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/rst_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/ilmb]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/dlmb]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/dlmb_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/ilmb_cntlr]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/lmb_bram_I]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cpu_unit/inst/iomodule_0]
